const swaggerJSDoc = require('swagger-jsdoc');
const Props = require('../util/api-properties');

// swagger definition
var swaggerDefinition = {
  info: {
    title: 'Givazon Swagger API',
    version: '1.0.0',
    description: '<p>Listing of  REST API specifications for Givazon project, Which are implemented using Express.js framework on top of Node.js. It mainly focusing on resources like <code>Child</code> ,<code>Transaction</code>. Each resource has its own set of <code>GET</code>, <code>POST ..</code> requests. </p>'+
        '<p>All <code>POST</code> and <code>PUT</code> services are protected and two different authentication mechanism are used in this project. </p>'+
        '<p></p>'+
      '<ul>'+
      '<li><b>Basic authorization</b>'+
      '<p>Static username and password is used for enforcing access controls and  authenticating user.</p></li>'+
      '<li><b>JWT Token based authorization</b>'+
      '<p>Dynamic and unique token will be generated for each User which will be expired periodically and can be generated by using post API of <code>Child</code> . Valid JWT token format for this authorization is <code>Bearer XXXX.XXXX.XXXX</code>'+
      '</li>'+
      '</ul>'+
       '<p><b>Note:</b> Use below <code>Authorize</code> button to login</p>',
  },
  host: Props.swaggerUrl.host,
  basePath: '/',
  schemes:[
  	'http',
  	'https'
  ],
  securityDefinitions:{
  	basicAuth:{
  		type: 'basic'
  	}
  }
};

// options for the swagger docs
var options = {
  // import swaggerDefinitions
  swaggerDefinition: swaggerDefinition,
  // path to the API docs
  apis: ['./routes/*.js'],
};

// initialize swagger-jsdoc
var swaggerSpec = swaggerJSDoc(options);
exports.SwaggerSpec=swaggerSpec;